/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** initData → JWT, текущая траектория, роль, права */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Подписанная строка запуска MAX Bridge. Проверяется по ТЗ §11.3. */
                        init_data: string;
                        /** @description Payload диплинка `startapp=`, если мини-приложение открыто по ссылке. */
                        start_param?: string | null;
                    };
                };
            };
            responses: {
                /** @description Сессия выдана */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                /** @description Подпись верна, но у пользователя нет траектории — нужно пройти онбординг у бота */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Цель, счётчики, следующий шаг, ближайшие сроки */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Home"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Подбор олимпиад под цель плюс блок «вне перечня»
         * @description Скоринг и сортировка — на сервере (ТЗ §6.1). Клиент показывает `items`
         *     в том порядке, в котором они пришли, и не пересчитывает ничего сам.
         */
        get: {
            parameters: {
                query?: {
                    /**
                     * @description Чипы экрана C3. `level1` — только I уровень, `soon` — дедлайн не дальше
                     *     16 дней, `online` — есть онлайн-отбор.
                     */
                    filter?: "all" | "level1" | "soon" | "online";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Recommendations"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/olympiads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Каталог олимпиад */
        get: {
            parameters: {
                query?: {
                    /** @description Поиск по названию и организатору, без учёта регистра. */
                    q?: string;
                    /** @description Код предмета, `subjects.code`. */
                    subject?: string;
                    /** @description Город финала, `olympiads.final_city`. */
                    city?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["OlympiadListItem"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/olympiads/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Карточка олимпиады
         * @description `id` — это `olympiad_profile_id`. Ответ содержит все профили той же
         *     олимпиады (`profiles`) для блока «Уровень по профилям», льготу в вузах
         *     ученика, условия, этапы и примеры вузов.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description `olympiad_profiles.id` */
                    id: components["parameters"]["ProfileId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OlympiadDetail"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/universities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Каталог вузов */
        get: {
            parameters: {
                query?: {
                    q?: string;
                    city?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["UniversityListItem"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/universities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Карточка вуза */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description `universities.id` */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UniversityDetail"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tracker": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Пункты трекера и предложения */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Tracker"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /**
         * Добавить олимпиаду в трекер
         * @description Повторное добавление того же профиля не создаёт дубль и отвечает 200
         *     с уже существующим пунктом. Если в траектории есть ученик, родителю
         *     здесь отвечают 403 — ему доступен только `POST /proposals` (ТЗ §3.1).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        olympiad_profile_id: string;
                    };
                };
            };
            responses: {
                /** @description Пункт уже был в трекере */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TrackerItem"];
                    };
                };
                /** @description Пункт создан */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TrackerItem"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tracker/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Убрать олимпиаду из трекера */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description `tracker_items.id` */
                    id: components["parameters"]["TrackerItemId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Удалено */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tracker/{id}/registered": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Отметить «зарегистрирован»
         * @description Отметку ставит любой участник. Остальные получают уведомление от бота,
         *     напоминания о регистрации по этой олимпиаде отменяются у всех (ТЗ §6.3).
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description `tracker_items.id` */
                    id: components["parameters"]["TrackerItemId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TrackerItem"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        post?: never;
        /** Снять отметку «зарегистрирован» */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description `tracker_items.id` */
                    id: components["parameters"]["TrackerItemId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TrackerItem"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Сроки месяца */
        get: {
            parameters: {
                query: {
                    /** @example 2026-10 */
                    month: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CalendarMonth"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Предложить олимпиаду ученику
         * @description Доступно родителю, когда ученик есть в траектории (ТЗ §3.1).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        olympiad_profile_id: string;
                    };
                };
            };
            responses: {
                /** @description Предложение по этому профилю уже ждёт ответа */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Proposal"];
                    };
                };
                /** @description Предложение создано */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Proposal"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                /** @description Олимпиада уже в трекере */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/proposals/{id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ученик принимает предложение — олимпиада попадает в трекер */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description `proposals.id` */
                    id: components["parameters"]["ProposalId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            proposal: components["schemas"]["Proposal"];
                            tracker_item: components["schemas"]["TrackerItem"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                /** @description Предложение уже закрыто */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/proposals/{id}/decline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ученик отклоняет предложение */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description `proposals.id` */
                    id: components["parameters"]["ProposalId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Proposal"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                /** @description Предложение уже закрыто */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/family": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Участники, создатель, активные ссылки */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Family"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/family/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Новая одноразовая ссылка-приглашение
         * @description Роль приглашённого выбирает тот, кто создаёт ссылку. Если ученик в
         *     траектории уже есть, доступна только роль `parent` (ТЗ §4.9, F42).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        role: components["schemas"]["Role"];
                    };
                };
            };
            responses: {
                /** @description Ссылка создана */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Invite"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description Ученик в траектории уже есть, вторую роль `kid` выдать нельзя */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/family/members/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Удалить участника
         * @description Только создатель и только не себя (ТЗ §3.1, F41).
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Участник удалён */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/family/leave": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Выйти из траектории
         * @description Создатель выйти не может — только удалить траекторию через /delete у бота (ТЗ §3.2).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Вышли */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Профиль ученика */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Profile"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Правка профиля ученика
         * @description Изменения видят все участники. Передаются только меняемые поля.
         *     `subject_codes` и `university_ids` — не меньше одного элемента.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProfilePatch"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Profile"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        trace?: never;
    };
    "/profile/universities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Заменить список вузов ученика
         * @description Отдельная ручка, потому что список вузов меняется не только из профиля,
         *     а ещё кнопкой «Добавить в мои вузы» в карточке вуза (ТЗ §10, F9/F25/F49).
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        university_ids: string[];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Profile"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * История личного чата с помощником
         * @description История своя у каждого участника и другим не видна (ТЗ F37).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["AiMessage"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /**
         * Вопрос помощнику
         * @description RAG только по нашей базе. Если ответа в базе нет, приходит
         *     `refused: true` и шаблон отказа со ссылкой на первоисточник (ТЗ F36).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        text: string;
                    };
                };
            };
            responses: {
                /** @description Ответ помощника */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            question: components["schemas"]["AiMessage"];
                            answer: components["schemas"]["AiMessage"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                /** @description Слишком часто */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                /** @enum {string} */
                code: "BAD_REQUEST" | "UNAUTHORIZED" | "FORBIDDEN" | "NOT_FOUND" | "CONFLICT" | "RATE_LIMITED" | "NOT_IMPLEMENTED" | "INTERNAL";
                /** @description Текст по-русски, показывается пользователю как есть. */
                message: string;
            };
        };
        /** @enum {string} */
        Role: "kid" | "parent";
        /**
         * @description `olympiads.kind`
         * @enum {string}
         */
        OlympiadKind: "perechen" | "vsosh" | "other";
        /**
         * @description Уровень профиля по перечню. `null` у ВсОШ и у олимпиад вне перечня.
         * @enum {string|null}
         */
        Level: "I" | "II" | "III" | null;
        /**
         * @description `benefits.benefit`
         * @enum {string}
         */
        BenefitKind: "bvi" | "score100" | "bvi_winners" | "extra_points";
        /** @enum {string} */
        StageKind: "registration" | "qualifying" | "final" | "school" | "municipal" | "regional";
        /**
         * @description Источник факта. Без него запись нельзя показывать с меткой «Факт» (ТЗ §6.2),
         *     клиент в этом случае рисует «данные уточняются».
         */
        Source: {
            id: string;
            /** @enum {string} */
            kind: "order" | "rules" | "site";
            /** @example Перечень олимпиад, приказ № 669 */
            title: string;
            /** Format: uri */
            url: string;
            /**
             * Format: date
             * @description Дата проверки. `null` — показывать без метки «Факт».
             */
            verified_at?: string | null;
        };
        /**
         * @description Оформление плитки. Оба поля могут быть `null`: клиент тогда строит
         *     аббревиатуру из названия и цвет из хеша идентификатора (src/lib/badge.ts),
         *     поэтому заполнять их на сервере необязательно.
         */
        Badge: {
            /** @example ВП */
            short_name: string | null;
            /** @example #6B2BFF */
            color: string | null;
        };
        /** @description Вычисляются сервером по матрице ТЗ §3.1 для текущего участника. */
        Permissions: {
            add_to_tracker: boolean;
            remove_from_tracker: boolean;
            propose: boolean;
            resolve_proposals: boolean;
            toggle_registered: boolean;
            edit_profile: boolean;
            invite: boolean;
            remove_members: boolean;
            leave: boolean;
            delete_trajectory: boolean;
        };
        SessionResponse: {
            /** @description JWT HS256 */
            token: string;
            /** Format: date-time */
            expires_at: string;
            session: components["schemas"]["Session"];
        };
        Session: {
            user: {
                /** Format: uuid */
                id: string;
                /** Format: int64 */
                max_user_id: number;
                /** @description Имя смотрящего. В текстах подставляется как `{me}`. */
                first_name: string;
            };
            member: {
                /** Format: uuid */
                id: string;
                role: components["schemas"]["Role"];
                is_creator: boolean;
                reminder_offsets: (30 | 7 | 3 | 1)[];
            };
            trajectory: components["schemas"]["TrajectorySummary"];
            permissions: components["schemas"]["Permissions"];
            /** @description Разобранный payload диплинка, если мини-приложение открыто по ссылке. */
            start_param: string | null;
        };
        TrajectorySummary: {
            /** Format: uuid */
            id: string;
            /** @description Имя ученика. В текстах подставляется как `{student}`. */
            student_name: string;
            /** @enum {integer} */
            grade: 8 | 9 | 10 | 11;
            /** @example 16 */
            region_code: string;
            /** @example Республика Татарстан */
            region_name: string;
            direction_id: string | null;
            /** @example Программная инженерия */
            direction_name: string | null;
            /** @enum {string} */
            goal_status: "known" | "suggested";
            /**
             * @description Есть ли в траектории активный участник с ролью `kid`. От этого
             *     зависит, добавляет родитель олимпиаду сам или предлагает (ТЗ §3.2).
             */
            has_kid: boolean;
            members_count: number;
        };
        /** @description Ближайший незарегистрированный пункт трекера (ТЗ §6.6). */
        NextStep: {
            /** Format: uuid */
            tracker_item_id: string;
            olympiad_profile_id: string;
            olympiad_name: string;
            /** @description «Регистрация» или название этапа ВсОШ — «Школьный этап». */
            stage_title: string;
            stage_kind: components["schemas"]["StageKind"];
            /** Format: date-time */
            deadline_at: string | null;
        };
        Home: {
            trajectory: components["schemas"]["TrajectorySummary"];
            tracker_count: number;
            registered_count: number;
            universities_count: number;
            /** @description Предложения, ждущие ответа ученика. Учитывается в бейдже вкладки «Трекер». */
            pending_proposals_count: number;
            /** @description `null`, когда всё отмечено — экран показывает «Всё по плану». */
            next_step: components["schemas"]["NextStep"] | null;
            /** @description Три ближайших срока из трекера. */
            upcoming: components["schemas"]["TrackerItem"][];
        };
        Recommendations: {
            /** @description Перечень и ВсОШ, уже отсортированы сервером. Клиент порядок не меняет. */
            items: components["schemas"]["OlympiadCard"][];
            /** @description Олимпиады вне перечня — отдельный блок, с основным списком не смешиваются (F16). */
            outside: components["schemas"]["OlympiadCard"][];
            /** @example Сначала ближайшие сроки и точное совпадение профиля */
            note: string;
        };
        OlympiadCard: components["schemas"]["Badge"] & {
            olympiad_profile_id: string;
            olympiad_id: string;
            name: string;
            organizer: string | null;
            kind: components["schemas"]["OlympiadKind"];
            level: components["schemas"]["Level"];
            subject_code: string;
            subject_name: string;
            /** @example Онлайн-отбор */
            format: string | null;
            is_online: boolean;
            final_city: string | null;
            /** Format: date-time */
            deadline_at: string | null;
            /**
             * @example Регистрация
             * @example Школьный этап
             */
            next_stage_title: string | null;
            /**
             * @description Строка о льготе в вузах ученика — «Иннополис, ВШЭ: БВИ» или «В твоих вузах льгот нет».
             * @example Иннополис, ВШЭ: БВИ
             */
            benefits_summary: string;
            /**
             * @description Причина рекомендации, 1–2 самых сильных фактора (ТЗ §6.1 п. 6).
             * @example Профиль совпадает с целью
             */
            reason: string;
            in_tracker: boolean;
            /**
             * @description `pending` — родитель уже предложил, ученик ещё не ответил.
             * @enum {string|null}
             */
            proposal_status: "pending" | null;
        };
        OlympiadListItem: components["schemas"]["Badge"] & {
            olympiad_id: string;
            name: string;
            organizer?: string | null;
            kind: components["schemas"]["OlympiadKind"];
            final_city?: string | null;
            /** @description Профиль, который откроется по тапу — совпадающий с предметами ученика либо первый. */
            primary_profile: {
                olympiad_profile_id: string;
                subject_code: string;
                subject_name: string;
                level: components["schemas"]["Level"];
            };
            profiles_count?: number;
        };
        /** @description Строка блока «Уровень по профилям». */
        ProfileLevel: {
            olympiad_profile_id: string;
            subject_code: string;
            subject_name: string;
            level: components["schemas"]["Level"];
            /** @description Профиль ученика — выделяется в интерфейсе. */
            is_mine: boolean;
        };
        /**
         * @description Льгота в конкретном вузе. `benefit: null` означает «не учитывает».
         *     Если `source` пуст, клиент не ставит метку «Факт» и пишет «данные уточняются» (F18).
         */
        BenefitRow: {
            university_id: string;
            university_name: string;
            university_short_name: string;
            city: string | null;
            color?: string | null;
            benefit: components["schemas"]["BenefitKind"] | null;
            /** @description Готовая подпись — «БВИ», «100 баллов», «БВИ победителям», «доп. баллы». */
            benefit_label: string | null;
            extra_points?: number | null;
            ege_min: number | null;
            diploma_grades?: number[] | null;
            note?: string | null;
            source: components["schemas"]["Source"] | null;
        };
        Stage: {
            id: string;
            kind: components["schemas"]["StageKind"];
            /**
             * @example Регистрация
             * @example Отборочный этап
             * @example Заключительный этап
             */
            title: string;
            /** @description Человеческая подпись под этапом — «до 25 сентября», «октябрь — ноябрь, онлайн». */
            subtitle: string | null;
            /** Format: date-time */
            starts_at?: string | null;
            /** Format: date-time */
            ends_at?: string | null;
            /** Format: date-time */
            deadline_at: string | null;
            is_online: boolean;
            /**
             * @description Для таймлайна: пройденные серым, ближайший выделен (F21).
             * @enum {string}
             */
            state: "past" | "current" | "future";
        };
        OlympiadDetail: components["schemas"]["OlympiadCard"] & {
            /** Format: uri */
            official_url: string | null;
            /** @description Все профили этой олимпиады, профиль ученика помечен `is_mine` (F17). */
            profiles: components["schemas"]["ProfileLevel"][];
            profiles_source: components["schemas"]["Source"] | null;
            /** @description По строке на каждый вуз ученика, включая «не учитывает» (F18). */
            benefits: components["schemas"]["BenefitRow"][];
            benefits_source: components["schemas"]["Source"] | null;
            /** @description Условия подтверждения льготы — порог ЕГЭ, классы, «БВИ в один вуз» (F19). */
            conditions: string[];
            stages: components["schemas"]["Stage"][];
            /** @description Ставит метку «Демо-даты» вместо «Факт», пока даты не выверены (ТЗ §0.5). */
            stages_are_demo: boolean;
            /** @description Блок «Почему подходит», метка «Рекомендация» (F20). */
            why: string;
            /** @description Все вузы базы, где эта олимпиада даёт льготу, — блок «Где даёт льготу» (F23). */
            benefit_universities: components["schemas"]["BenefitRow"][];
        };
        UniversityListItem: {
            id: string;
            short_name: string;
            name: string;
            city: string | null;
            color?: string | null;
            /** @description Сколько олимпиад дают в этом вузе БВИ или 100 баллов. */
            benefit_olympiads_count: number;
            /** @description Вуз входит в список ученика. */
            is_mine: boolean;
        };
        UniversityDetail: components["schemas"]["UniversityListItem"] & {
            directions: string[];
            /** @example от 75 баллов по профильному предмету */
            ege_note: string | null;
            /** Format: uri */
            rules_url: string | null;
            /** Format: date */
            rules_verified_at: string | null;
            /** @description Олимпиады, дающие льготу в этом вузе, с переходом в карточку (F26). */
            olympiads: (components["schemas"]["Badge"] & {
                olympiad_profile_id: string;
                olympiad_id?: string;
                name: string;
                subject_name?: string;
                level: components["schemas"]["Level"];
                benefit: components["schemas"]["BenefitKind"];
                benefit_label?: string;
            })[];
        };
        TrackerItem: components["schemas"]["Badge"] & {
            /** Format: uuid */
            id: string;
            olympiad_profile_id: string;
            olympiad_id: string;
            olympiad_name: string;
            subject_name: string;
            kind: components["schemas"]["OlympiadKind"];
            level: components["schemas"]["Level"];
            /** Format: date-time */
            deadline_at: string | null;
            /**
             * @example Регистрация
             * @example Школьный этап
             * @example Отборочный этап
             */
            next_stage_title: string | null;
            /** Format: date-time */
            registered_at: string | null;
            /** @description Кто поставил отметку — строка «Отметила Ольга» (F31). */
            registered_by: components["schemas"]["MemberBrief"] | null;
            /** @description Кто добавил — пометка «добавил(а) <имя>» (ТЗ §3.2). */
            added_by: components["schemas"]["MemberBrief"] | null;
        };
        Proposal: components["schemas"]["Badge"] & {
            /** Format: uuid */
            id: string;
            olympiad_profile_id: string;
            olympiad_id: string;
            olympiad_name: string;
            /** Format: date-time */
            deadline_at: string | null;
            /** @enum {string} */
            status: "pending" | "accepted" | "declined";
            proposed_by: components["schemas"]["MemberBrief"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            resolved_at: string | null;
        };
        Tracker: {
            items: components["schemas"]["TrackerItem"][];
            /**
             * @description Ученику — предложения, ждущие его ответа. Родителю — его же
             *     предложения со статусом «ждёт подтверждения» (ТЗ E1/E3).
             */
            proposals: components["schemas"]["Proposal"][];
        };
        CalendarMonth: {
            month: string;
            days: {
                /** Format: date */
                date: string;
                items: components["schemas"]["TrackerItem"][];
            }[];
        };
        MemberBrief: {
            /** Format: uuid */
            id: string;
            name: string;
            role: components["schemas"]["Role"];
        };
        Member: components["schemas"]["MemberBrief"] & {
            is_creator: boolean;
            is_me: boolean;
            /** @description Сервер уже учёл матрицу прав — создателя и себя удалить нельзя. */
            can_remove: boolean;
            color?: string | null;
            /** Format: date-time */
            joined_at: string;
        };
        Invite: {
            /** Format: uuid */
            id: string;
            token: string;
            /**
             * Format: uri
             * @description Готовая ссылка `https://max.ru/<bot>?start=inv_<token>` (F39).
             */
            url: string;
            role: components["schemas"]["Role"];
            /** Format: date-time */
            created_at: string;
        };
        Family: {
            trajectory: components["schemas"]["TrajectorySummary"];
            members: components["schemas"]["Member"][];
            /** @description Активные, ещё не использованные ссылки. */
            invites: components["schemas"]["Invite"][];
        };
        Profile: {
            student_name: string;
            /** @enum {integer} */
            grade: 8 | 9 | 10 | 11;
            region_code: string;
            region_name: string;
            subjects: {
                code: string;
                name: string;
            }[];
            direction_id: string | null;
            direction_name: string | null;
            /** @enum {string} */
            goal_status: "known" | "suggested";
            universities: components["schemas"]["UniversityListItem"][];
            /** @description Имена остальных участников — «Изменения увидят все участники: Ольга, Игорь». */
            other_member_names: string[];
        };
        ProfilePatch: {
            student_name?: string;
            /** @enum {integer} */
            grade?: 8 | 9 | 10 | 11;
            region_code?: string;
            subject_codes?: string[];
            direction_id?: string;
            university_ids?: string[];
        };
        /** @description Ссылка на карточку нашей базы — кнопка «Карточка «…»» под ответом (F35). */
        AiCardRef: {
            /** @enum {string} */
            type: "olympiad" | "university";
            /** @description `olympiad_profile_id` или `universities.id` — по чему открывать карточку. */
            id: string;
            title: string;
        };
        AiMessage: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            role: "user" | "assistant";
            text: string;
            card_refs: components["schemas"]["AiCardRef"][];
            /** @description Ссылки на первоисточники под ответом. */
            sources: components["schemas"]["Source"][];
            /** @description `true` — честное «данных нет» (F36). Клиент рисует жёлтым. */
            refused: boolean;
            /** Format: date-time */
            created_at: string;
        };
    };
    responses: {
        /** @description Некорректный запрос */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Нет или истёк JWT — клиент повторяет POST /session */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Действие запрещено матрицей прав ТЗ §3.1 */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Объект не найден */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description `olympiad_profiles.id` */
        ProfileId: string;
        /** @description `tracker_items.id` */
        TrackerItemId: string;
        /** @description `proposals.id` */
        ProposalId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
