/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** initData → JWT, текущая траектория, роль, права */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Подписанная строка запуска MAX Bridge. Проверяется по ТЗ §11.3. */
                        init_data: string;
                        /** @description Payload диплинка `startapp=`, если мини-приложение открыто по ссылке. */
                        start_param?: string | null;
                    };
                };
            };
            responses: {
                /** @description Сессия выдана */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                /** @description Подпись верна, но у пользователя нет траектории — нужно пройти онбординг у бота */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Цель, счётчики, следующий шаг, ближайшие сроки */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Home"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Подбор олимпиад под цель плюс блок «вне перечня»
         * @description Скоринг и сортировка — на сервере (ТЗ §6.1). Клиент показывает `items`
         *     в том порядке, в котором они пришли, и не пересчитывает ничего сам.
         */
        get: {
            parameters: {
                query?: {
                    /**
                     * @description Чипы экрана C3. `level1` — только I уровень, `soon` — дедлайн не дальше
                     *     16 дней, `online` — есть онлайн-отбор.
                     */
                    filter?: "all" | "level1" | "soon" | "online";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Recommendations"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/olympiads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Каталог олимпиад */
        get: {
            parameters: {
                query?: {
                    /** @description Поиск по названию и организатору, без учёта регистра. */
                    q?: string;
                    /** @description Код предмета, `subjects.code`. */
                    subject?: string;
                    /** @description Город финала, `olympiads.final_city`. */
                    city?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["OlympiadListItem"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/olympiads/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Карточка олимпиады
         * @description `id` — это `olympiad_profile_id`. Ответ содержит все профили той же
         *     олимпиады (`profiles`) для блока «Уровень по профилям», льготу в вузах
         *     ученика, условия, этапы и примеры вузов.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description `olympiad_profiles.id` */
                    id: components["parameters"]["ProfileId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OlympiadDetail"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/universities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Каталог вузов */
        get: {
            parameters: {
                query?: {
                    q?: string;
                    city?: string;
                    /** @description `directions.id` — только вузы, где есть программа этого направления. */
                    direction?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["UniversityListItem"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/universities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Карточка вуза */
        get: {
            parameters: {
                query?: {
                    /**
                     * @description `Program.id` направления этого вуза: `olympiads` — только с льготой
                     *     на это направление. Направление другого вуза — 404.
                     */
                    program?: string;
                };
                header?: never;
                path: {
                    /** @description `universities.id` */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UniversityDetail"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/directions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Направления — справочник целей для правки профиля */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["Direction"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tracker": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Пункты трекера и предложения */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Tracker"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /**
         * Добавить олимпиаду в трекер
         * @description Повторное добавление того же профиля не создаёт дубль и отвечает 200
         *     с уже существующим пунктом. Если в траектории есть ученик, родителю
         *     здесь отвечают 403 — ему доступен только `POST /proposals` (ТЗ §3.1).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        olympiad_profile_id: string;
                    };
                };
            };
            responses: {
                /** @description Пункт уже был в трекере */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TrackerItem"];
                    };
                };
                /** @description Пункт создан */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TrackerItem"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tracker/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Убрать олимпиаду из трекера */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description `tracker_items.id` */
                    id: components["parameters"]["TrackerItemId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Удалено */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tracker/{id}/registered": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Отметить «зарегистрирован»
         * @description Отметку ставит любой участник. Остальные получают уведомление от бота,
         *     напоминания о регистрации по этой олимпиаде отменяются у всех (ТЗ §6.3).
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description `tracker_items.id` */
                    id: components["parameters"]["TrackerItemId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TrackerItem"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        post?: never;
        /** Снять отметку «зарегистрирован» */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description `tracker_items.id` */
                    id: components["parameters"]["TrackerItemId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TrackerItem"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Сроки месяца */
        get: {
            parameters: {
                query: {
                    /** @example 2026-10 */
                    month: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CalendarMonth"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calendar/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ссылка на файл календаря со сроками
         * @description Файл .ics забирает браузер телефона или MAX, а не мини-приложение, —
         *     заголовок Authorization им не передать. Поэтому сначала выдаётся
         *     ссылка: путь относительно базового адреса API с подписанным токеном.
         *     Ссылка живёт десять минут и открывает только календарь своей семьи.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CalendarLink"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calendar.ics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Файл календаря (.ics) со всеми будущими сроками трекера
         * @description Без сессии: доступ по токену из GET /calendar/link. Срок этапа —
         *     событие на весь день по Москве с напоминанием накануне в 9:00. Этапы,
         *     закрытые отметкой «зарегистрирован», не выгружаются. Просроченный,
         *     чужой или испорченный токен и удалённый участник — 404.
         */
        get: {
            parameters: {
                query: {
                    token: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Календарь RFC 5545 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/calendar": string;
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Предложить олимпиаду ученику
         * @description Доступно родителю, когда ученик есть в траектории (ТЗ §3.1).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        olympiad_profile_id: string;
                    };
                };
            };
            responses: {
                /** @description Предложение по этому профилю уже ждёт ответа */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Proposal"];
                    };
                };
                /** @description Предложение создано */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Proposal"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                /** @description Олимпиада уже в трекере */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/proposals/{id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ученик принимает предложение — олимпиада попадает в трекер */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description `proposals.id` */
                    id: components["parameters"]["ProposalId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            proposal: components["schemas"]["Proposal"];
                            tracker_item: components["schemas"]["TrackerItem"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                /** @description Предложение уже закрыто */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/proposals/{id}/decline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ученик отклоняет предложение */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description `proposals.id` */
                    id: components["parameters"]["ProposalId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Proposal"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                /** @description Предложение уже закрыто */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/family": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Участники, создатель, активные ссылки */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Family"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/family/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Новая одноразовая ссылка-приглашение
         * @description Роль приглашённого выбирает тот, кто создаёт ссылку. Если ученик в
         *     траектории уже есть, доступна только роль `parent` (ТЗ §4.9, F42).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        role: components["schemas"]["Role"];
                    };
                };
            };
            responses: {
                /** @description Ссылка создана */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Invite"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description Ученик в траектории уже есть, вторую роль `kid` выдать нельзя */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/family/members/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Удалить участника
         * @description Только создатель и только не себя (ТЗ §3.1, F41).
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Участник удалён */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/family/leave": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Выйти из траектории
         * @description Создатель выйти не может — только удалить траекторию через /delete у бота (ТЗ §3.2).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Вышли */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Профиль ученика */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Profile"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Правка профиля ученика
         * @description Изменения видят все участники. Передаются только меняемые поля.
         *     `subject_codes` и `university_ids` — не меньше одного элемента.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProfilePatch"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Profile"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        trace?: never;
    };
    "/profile/universities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Заменить список вузов ученика
         * @description Отдельная ручка, потому что список вузов меняется не только из профиля,
         *     а ещё кнопкой «Добавить в мои вузы» в карточке вуза (ТЗ §10, F9/F25/F49).
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Может быть пустым — вузы выбирать не обязательно (F9). */
                        university_ids: string[];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Profile"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/programs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Заменить сохранённые направления вузов
         * @description Направления подготовки, которые ученик сохранил в карточке вуза.
         *     Вузы этих направлений добавляются к вузам ученика; убранный вуз
         *     (`PUT /profile/universities`) уносит и свои направления.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description `Program.id`; может быть пустым. */
                        program_ids: string[];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Profile"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/chats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Чаты с помощником
         * @description Свои чаты участника, свежие сверху — по времени последней реплики.
         *     Другим участникам не видны (ТЗ F37). Пустых чатов не бывает: чат
         *     появляется вместе с первым вопросом.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["AiChat"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /**
         * Новый чат с первым вопросом
         * @description Создаёт чат и сразу отвечает на первый вопрос. Название — «Чат 23
         *     сентября» по дню вопроса в часовом поясе траектории (ТЗ F59).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AiQuestion"];
                };
            };
            responses: {
                /** @description Чат создан, ответ помощника */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AiExchange"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                429: components["responses"]["RateLimited"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/chats/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Переименовать чат
         * @description Пробелы по краям отбрасываются; остаётся от 1 до 60 символов (ТЗ F59).
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description `ai_chats.id`. Чужой чат для участника не существует — 404 (ТЗ F37). */
                    id: components["parameters"]["ChatId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        title: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AiChat"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/ai/chats/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Реплики чата
         * @description 50 последних реплик, от старых к новым.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description `ai_chats.id`. Чужой чат для участника не существует — 404 (ТЗ F37). */
                    id: components["parameters"]["ChatId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["AiMessage"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        /**
         * Вопрос помощнику в чате
         * @description RAG только по нашей базе. Карточки ищутся по тексту этого вопроса;
         *     модель видит ещё 10 предыдущих реплик чата и карточки, на которые
         *     ссылались ответы в них (ТЗ F60). Если ответа в базе нет, приходит
         *     `refused: true` и шаблон отказа со ссылкой на первоисточник (ТЗ F36).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description `ai_chats.id`. Чужой чат для участника не существует — 404 (ТЗ F37). */
                    id: components["parameters"]["ChatId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AiQuestion"];
                };
            };
            responses: {
                /** @description Ответ помощника */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AiExchange"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                429: components["responses"]["RateLimited"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                /** @enum {string} */
                code: "BAD_REQUEST" | "UNAUTHORIZED" | "FORBIDDEN" | "NOT_FOUND" | "CONFLICT" | "RATE_LIMITED" | "NOT_IMPLEMENTED" | "INTERNAL";
                /** @description Текст по-русски, показывается пользователю как есть. */
                message: string;
            };
        };
        /** @enum {string} */
        Role: "kid" | "parent";
        /**
         * @description `olympiads.kind`
         * @enum {string}
         */
        OlympiadKind: "perechen" | "vsosh" | "other";
        /**
         * @description Уровень профиля по перечню. `null` у ВсОШ и у олимпиад вне перечня.
         * @enum {string|null}
         */
        Level: "I" | "II" | "III" | null;
        /**
         * @description `benefits.benefit`
         * @enum {string}
         */
        BenefitKind: "bvi" | "score100" | "bvi_winners" | "extra_points";
        /** @enum {string} */
        StageKind: "registration" | "qualifying" | "final" | "school" | "municipal" | "regional";
        /**
         * @description Источник факта. Без него запись нельзя показывать с меткой «Факт» (ТЗ §6.2),
         *     клиент в этом случае рисует «данные уточняются».
         */
        Source: {
            id: string;
            /** @enum {string} */
            kind: "order" | "rules" | "site";
            /** @example Перечень олимпиад, приказ № 669 */
            title: string;
            /** Format: uri */
            url: string;
            /**
             * Format: date
             * @description Дата проверки. `null` — показывать без метки «Факт».
             */
            verified_at?: string | null;
        };
        /**
         * @description Оформление плитки. Оба поля могут быть `null`: клиент тогда строит
         *     аббревиатуру из названия и цвет из хеша идентификатора (src/lib/badge.ts),
         *     поэтому заполнять их на сервере необязательно.
         */
        Badge: {
            /** @example ВП */
            short_name: string | null;
            /** @example #6B2BFF */
            color: string | null;
        };
        /** @description Вычисляются сервером по матрице ТЗ §3.1 для текущего участника. */
        Permissions: {
            add_to_tracker: boolean;
            remove_from_tracker: boolean;
            propose: boolean;
            resolve_proposals: boolean;
            toggle_registered: boolean;
            edit_profile: boolean;
            invite: boolean;
            remove_members: boolean;
            leave: boolean;
            delete_trajectory: boolean;
        };
        SessionResponse: {
            /** @description JWT HS256 */
            token: string;
            /** Format: date-time */
            expires_at: string;
            session: components["schemas"]["Session"];
        };
        Session: {
            user: {
                /** Format: uuid */
                id: string;
                /** Format: int64 */
                max_user_id: number;
                /** @description Имя смотрящего. В текстах подставляется как `{me}`. */
                first_name: string;
            };
            member: {
                /** Format: uuid */
                id: string;
                role: components["schemas"]["Role"];
                is_creator: boolean;
                reminder_offsets: (30 | 7 | 3 | 1)[];
            };
            trajectory: components["schemas"]["TrajectorySummary"];
            permissions: components["schemas"]["Permissions"];
            /** @description Разобранный payload диплинка, если мини-приложение открыто по ссылке. */
            start_param: string | null;
        };
        TrajectorySummary: {
            /** Format: uuid */
            id: string;
            /** @description Имя ученика. В текстах подставляется как `{student}`. */
            student_name: string;
            /** @enum {integer} */
            grade: 8 | 9 | 10 | 11;
            /**
             * @description Код субъекта РФ; пустая строка — регион не указан («Не важно»), напоминания по московскому времени.
             * @example 16
             */
            region_code: string;
            /**
             * @description Пустая строка, если регион не указан.
             * @example Республика Татарстан
             */
            region_name: string;
            /** @description Направления-цели в порядке выбора (F8). Пусто — ученик пока не решил. */
            directions: components["schemas"]["Direction"][];
            /**
             * @description known — направления выбраны, exploring — пока не решил,
             *     suggested — старые траектории, где цель предлагал опросник.
             * @enum {string}
             */
            goal_status: "known" | "suggested" | "exploring";
            /**
             * @description Есть ли в траектории активный участник с ролью `kid`. От этого
             *     зависит, добавляет родитель олимпиаду сам или предлагает (ТЗ §3.2).
             */
            has_kid: boolean;
            members_count: number;
        };
        /** @description Ближайший незарегистрированный пункт трекера (ТЗ §6.6). */
        NextStep: {
            /** Format: uuid */
            tracker_item_id: string;
            olympiad_profile_id: string;
            olympiad_name: string;
            /** @description «Регистрация» или название этапа ВсОШ — «Школьный этап». */
            stage_title: string;
            stage_kind: components["schemas"]["StageKind"];
            /** Format: date-time */
            deadline_at: string | null;
        };
        Home: {
            trajectory: components["schemas"]["TrajectorySummary"];
            tracker_count: number;
            registered_count: number;
            universities_count: number;
            /** @description Предложения, ждущие ответа ученика. Учитывается в бейдже вкладки «Трекер». */
            pending_proposals_count: number;
            /** @description `null`, когда всё отмечено — экран показывает «Всё по плану». */
            next_step: components["schemas"]["NextStep"] | null;
            /** @description Три ближайших срока из трекера. */
            upcoming: components["schemas"]["TrackerItem"][];
        };
        Recommendations: {
            /** @description Перечень и ВсОШ, уже отсортированы сервером. Клиент порядок не меняет. */
            items: components["schemas"]["OlympiadCard"][];
            /** @description Олимпиады вне перечня — отдельный блок, с основным списком не смешиваются (F16). */
            outside: components["schemas"]["OlympiadCard"][];
            /** @example Сначала ближайшие сроки и точное совпадение профиля */
            note: string;
        };
        OlympiadCard: components["schemas"]["Badge"] & {
            olympiad_profile_id: string;
            olympiad_id: string;
            name: string;
            organizer: string | null;
            kind: components["schemas"]["OlympiadKind"];
            level: components["schemas"]["Level"];
            subject_code: string;
            subject_name: string;
            /** @example Онлайн-отбор */
            format: string | null;
            is_online: boolean;
            final_city: string | null;
            /** Format: date-time */
            deadline_at: string | null;
            /**
             * @example Регистрация
             * @example Школьный этап
             */
            next_stage_title: string | null;
            /**
             * @description Строка о льготе в вузах ученика — «Иннополис, ВШЭ: БВИ» или «В твоих вузах льгот нет».
             * @example Иннополис, ВШЭ: БВИ
             */
            benefits_summary: string;
            /**
             * @description Причина рекомендации, 1–2 самых сильных фактора (ТЗ §6.1 п. 6).
             * @example Профиль совпадает с целью
             */
            reason: string;
            in_tracker: boolean;
            /**
             * @description `pending` — родитель уже предложил, ученик ещё не ответил.
             * @enum {string|null}
             */
            proposal_status: "pending" | null;
        };
        OlympiadListItem: components["schemas"]["Badge"] & {
            olympiad_id: string;
            name: string;
            organizer?: string | null;
            kind: components["schemas"]["OlympiadKind"];
            final_city?: string | null;
            /** @description Профиль, который откроется по тапу — совпадающий с предметами ученика либо первый. */
            primary_profile: {
                olympiad_profile_id: string;
                subject_code: string;
                subject_name: string;
                level: components["schemas"]["Level"];
            };
            profiles_count?: number;
        };
        /** @description Строка блока «Уровень по профилям». */
        ProfileLevel: {
            olympiad_profile_id: string;
            subject_code: string;
            subject_name: string;
            level: components["schemas"]["Level"];
            /** @description Профиль ученика — выделяется в интерфейсе. */
            is_mine: boolean;
        };
        /** @description Что получит победитель или призёр в вузе. */
        BenefitGrant: {
            /** @enum {string} */
            kind: "bvi" | "score100" | "extra_points";
            /** @description Готовая подпись — «БВИ», «100 баллов», «+3 балла». */
            label: string;
        };
        /**
         * @description Столбец таблицы льгот (F18, F19): `winner` и `prizer` — что получат победитель и призёр,
         *     `ege` — порог ЕГЭ, `extra_points` — доп. баллы у олимпиад вне перечня.
         * @enum {string}
         */
        BenefitColumn: "winner" | "prizer" | "ege" | "extra_points";
        /**
         * @description Льгота в конкретном вузе. `benefit: null` означает «не учитывает».
         *     Если `source` пуст, клиент не ставит метку «Факт» и пишет «данные уточняются» (F18).
         */
        BenefitRow: {
            university_id: string;
            university_name: string;
            university_short_name: string;
            /** @description Как вуз называют коротко в таблице и тексте — «ВШЭ», «Иннополис». */
            university_nick: string;
            city: string | null;
            color?: string | null;
            benefit: components["schemas"]["BenefitKind"] | null;
            /** @description Готовая подпись — «БВИ», «100 баллов», «БВИ победителям», «доп. баллы». */
            benefit_label: string | null;
            /** @description Что получит победитель; `null` — вуз олимпиаду не учитывает. */
            winner: components["schemas"]["BenefitGrant"] | null;
            /** @description Что получит призёр; `null` — призёру льготы нет или вуз олимпиаду не учитывает. */
            prizer: components["schemas"]["BenefitGrant"] | null;
            extra_points?: number | null;
            ege_min: number | null;
            /** @description Верхняя граница порога, если он зависит от программы — «75–85». */
            ege_max: number | null;
            diploma_grades?: number[] | null;
            note?: string | null;
            source: components["schemas"]["Source"] | null;
            /**
             * @description Чем условия в этом вузе отличаются от общих `OlympiadDetail.conditions`, кроме того, что
             *     видно в столбцах таблицы (F19): другой предмет ЕГЭ, класс диплома — только если вуз не
             *     засчитает диплом этого года. Есть только в `OlympiadDetail.benefits`, пусто — поля нет.
             * @example [
             *       "Призёру — 100 баллов вместо БВИ",
             *       "Порог ЕГЭ от 75 до 80 — зависит от программы"
             *     ]
             */
            conditions?: string[];
        };
        Stage: {
            id: string;
            kind: components["schemas"]["StageKind"];
            /**
             * @example Регистрация
             * @example Отборочный этап
             * @example Заключительный этап
             */
            title: string;
            /** @description Человеческая подпись под этапом — «до 25 сентября», «октябрь — ноябрь, онлайн». */
            subtitle: string | null;
            /** Format: date-time */
            starts_at?: string | null;
            /** Format: date-time */
            ends_at?: string | null;
            /** Format: date-time */
            deadline_at: string | null;
            is_online: boolean;
            /**
             * @description Для таймлайна: пройденные серым, ближайший выделен (F21).
             * @enum {string}
             */
            state: "past" | "current" | "future";
        };
        OlympiadDetail: components["schemas"]["OlympiadCard"] & {
            /** Format: uri */
            official_url: string | null;
            /** @description Что это за олимпиада — пара предложений по официальному сайту. Пусто — блок не показывается. */
            description: string | null;
            /** @description Все профили этой олимпиады, профиль ученика помечен `is_mine` (F17). */
            profiles: components["schemas"]["ProfileLevel"][];
            profiles_source: components["schemas"]["Source"] | null;
            /**
             * @description По строке на каждый вуз ученика, включая «не учитывает» (F18). Сначала самые выгодные,
             *     дальше по алфавиту `university_nick`; «не учитывает» — в конце.
             */
            benefits: components["schemas"]["BenefitRow"][];
            /**
             * @description Столбцы таблицы льгот. Вне перечня — только `extra_points`. `ege` — если порог в вузах
             *     ученика разный или зависит от программы; одинаковый — в общих `conditions`.
             */
            benefit_columns: components["schemas"]["BenefitColumn"][];
            benefits_source: components["schemas"]["Source"] | null;
            /**
             * @description Общие условия подтверждения льготы в вузах ученика — диплом, ЕГЭ, «БВИ в один вуз» (F19).
             *     Порог ЕГЭ здесь, только если его нет в `benefit_columns`. Своё у вуза — в `benefits[].conditions`. Если вузы ученика льготы не дают, условия
             *     собраны по всем вузам базы и включают их особенности.
             */
            conditions: string[];
            stages: components["schemas"]["Stage"][];
            /** @description Ставит метку «Демо-даты» вместо «Факт», пока даты не выверены (ТЗ §0.5). */
            stages_are_demo: boolean;
            /** @description Блок «Почему подходит», метка «Рекомендация» (F20). */
            why: string;
            /** @description Вузы базы, где эта олимпиада даёт льготу, кроме вузов ученика (они в benefits), — блок «Где ещё даёт льготу» (F23). */
            benefit_universities: components["schemas"]["BenefitRow"][];
        };
        Direction: {
            /** @example napr-09-03-04 */
            id: string;
            /** @example Программная инженерия */
            name: string;
        };
        UniversityListItem: {
            id: string;
            short_name: string;
            name: string;
            city: string | null;
            color?: string | null;
            /** @description Сколько олимпиад дают в этом вузе БВИ или 100 баллов. */
            benefit_olympiads_count: number;
            /** @description Вуз входит в список ученика. */
            is_mine: boolean;
        };
        /** @description Направление подготовки вуза (образовательная программа). */
        Program: {
            /** @example msu__prikladnaya-matematika-i-informatika */
            id: string;
            university_id: string;
            /** @example МГУ */
            university_short_name: string;
            /** @example Прикладная математика и информатика */
            name: string;
            /** @example Факультет вычислительной математики и кибернетики */
            faculty: string | null;
            /**
             * @description Код направления по ОКСО.
             * @example 01.03.02
             */
            code: string | null;
            /** @description `Direction.id`, если код входит в справочник целей. */
            direction_id: string | null;
            /** @description Бюджетные места; null — число не подтверждено источником. */
            budget_places: number | null;
            /** @description Сколько олимпиад дают на это направление БВИ или 100 баллов. */
            olympiads_count: number;
            /** @description Ученик сохранил направление. */
            is_mine: boolean;
        };
        UniversityDetail: components["schemas"]["UniversityListItem"] & {
            /** @description Топ названий направлений вуза — для вузов без программ в базе. */
            directions: string[];
            /**
             * @description Направления подготовки вуза: сохранённые учеником первыми, за ними —
             *     по направлениям-целям ученика, дальше по названию.
             */
            programs: components["schemas"]["Program"][];
            /** @example от 75 баллов по профильному предмету */
            ege_note: string | null;
            /** Format: uri */
            rules_url: string | null;
            /** Format: date */
            rules_verified_at: string | null;
            /** @description Что это за вуз — пара предложений по официальному сайту. */
            description: string | null;
            /** Format: uri */
            site_url: string | null;
            /** @description Олимпиады, дающие льготу в этом вузе, с переходом в карточку (F26). */
            olympiads: (components["schemas"]["Badge"] & {
                olympiad_profile_id: string;
                olympiad_id?: string;
                name: string;
                subject_name?: string;
                level: components["schemas"]["Level"];
                benefit: components["schemas"]["BenefitKind"];
                benefit_label?: string;
            })[];
        };
        TrackerItem: components["schemas"]["Badge"] & {
            /** Format: uuid */
            id: string;
            olympiad_profile_id: string;
            olympiad_id: string;
            olympiad_name: string;
            subject_name: string;
            kind: components["schemas"]["OlympiadKind"];
            level: components["schemas"]["Level"];
            /** Format: date-time */
            deadline_at: string | null;
            /**
             * @example Регистрация
             * @example Школьный этап
             * @example Отборочный этап
             */
            next_stage_title: string | null;
            /** Format: date-time */
            registered_at: string | null;
            /** @description Кто поставил отметку — строка «Отметила Ольга» (F31). */
            registered_by: components["schemas"]["MemberBrief"] | null;
            /** @description Кто добавил — пометка «добавил(а) <имя>» (ТЗ §3.2). */
            added_by: components["schemas"]["MemberBrief"] | null;
        };
        Proposal: components["schemas"]["Badge"] & {
            /** Format: uuid */
            id: string;
            olympiad_profile_id: string;
            olympiad_id: string;
            olympiad_name: string;
            /** Format: date-time */
            deadline_at: string | null;
            /** @enum {string} */
            status: "pending" | "accepted" | "declined";
            proposed_by: components["schemas"]["MemberBrief"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            resolved_at: string | null;
        };
        Tracker: {
            items: components["schemas"]["TrackerItem"][];
            /**
             * @description Ученику — предложения, ждущие его ответа. Родителю — его же
             *     предложения со статусом «ждёт подтверждения» (ТЗ E1/E3).
             */
            proposals: components["schemas"]["Proposal"][];
        };
        CalendarLink: {
            /**
             * @description Путь относительно базового адреса API, с токеном.
             * @example /calendar.ics?token=eyJhbGciOiJIUzI1NiJ9…
             */
            url: string;
            /** Format: date-time */
            expires_at: string;
        };
        CalendarMonth: {
            month: string;
            days: {
                /** Format: date */
                date: string;
                items: components["schemas"]["TrackerItem"][];
            }[];
        };
        MemberBrief: {
            /** Format: uuid */
            id: string;
            name: string;
            role: components["schemas"]["Role"];
        };
        Member: components["schemas"]["MemberBrief"] & {
            is_creator: boolean;
            is_me: boolean;
            /** @description Сервер уже учёл матрицу прав — создателя и себя удалить нельзя. */
            can_remove: boolean;
            color?: string | null;
            /** Format: date-time */
            joined_at: string;
        };
        Invite: {
            /** Format: uuid */
            id: string;
            token: string;
            /**
             * Format: uri
             * @description Готовая ссылка `https://max.ru/<bot>?start=inv_<token>` (F39).
             */
            url: string;
            role: components["schemas"]["Role"];
            /** Format: date-time */
            created_at: string;
        };
        Family: {
            trajectory: components["schemas"]["TrajectorySummary"];
            members: components["schemas"]["Member"][];
            /** @description Активные, ещё не использованные ссылки. */
            invites: components["schemas"]["Invite"][];
        };
        Profile: {
            student_name: string;
            /** @enum {integer} */
            grade: 8 | 9 | 10 | 11;
            /** @description Код субъекта РФ; пустая строка — регион не указан. */
            region_code: string;
            /** @description Пустая строка, если регион не указан. */
            region_name: string;
            subjects: {
                code: string;
                name: string;
            }[];
            directions: components["schemas"]["Direction"][];
            /** @enum {string} */
            goal_status: "known" | "suggested" | "exploring";
            /**
             * @deprecated
             * @description Первое место из `places` — код субъекта РФ; null — не важно. Устарело, вместо него `places`.
             * @example 77
             */
            target_region_code: string | null;
            /**
             * @deprecated
             * @example Москва
             */
            target_region_name: string | null;
            /**
             * @description Опыт в олимпиадах: none — пока не было, school — школьный или муниципальный этап, region — региональный и выше. null — не спрашивали, подбор считает как none.
             * @enum {string|null}
             */
            experience: "none" | "school" | "region" | null;
            /**
             * @description Город ученика, если известен (из поиска или геолокации в боте).
             * @example Казань
             */
            home_city: string | null;
            /** @description Где ученик хочет учиться, в порядке выбора; пустой список — не важно. */
            places: components["schemas"]["Place"][];
            /** @description Может быть пустым — вузы выбирать не обязательно (F9). */
            universities: components["schemas"]["UniversityListItem"][];
            /** @description Направления вузов, сохранённые в каталоге; их вузы — в `universities`. */
            programs: components["schemas"]["Program"][];
            /** @description Имена остальных участников — «Изменения увидят все участники: Ольга, Игорь». */
            other_member_names: string[];
        };
        ProfilePatch: {
            student_name?: string;
            /** @enum {integer} */
            grade?: 8 | 9 | 10 | 11;
            /** @description Код субъекта РФ, часовой пояс — по нему; пустая строка — регион не указан, время московское. */
            region_code?: string;
            subject_codes?: string[];
            /** @description Направления в порядке выбора; пустой список — «пока не решил». */
            direction_ids?: string[];
            /**
             * @deprecated
             * @description Код субъекта РФ, где ученик хочет учиться; пустая строка — не важно. Устарело, вместо него `places`; игнорируется, если передан `places`.
             */
            target_region_code?: string;
            /** @description Где ученик хочет учиться; пустой список — не важно, повторы отбрасываются. */
            places?: {
                /** @example 16 */
                region_code: string;
                /** @description Город внутри региона; null — весь регион. */
                city?: string | null;
            }[];
            /** @enum {string} */
            experience?: "none" | "school" | "region";
            university_ids?: string[];
        };
        Place: {
            /** @example 16 */
            region_code: string;
            /** @example Республика Татарстан */
            region_name: string;
            /**
             * @description Город внутри региона; null — весь регион.
             * @example Казань
             */
            city: string | null;
        };
        /** @description Ссылка на карточку нашей базы — кнопка «Карточка «…»» под ответом (F35). */
        AiCardRef: {
            /** @enum {string} */
            type: "olympiad" | "university";
            /** @description `olympiad_profile_id` или `universities.id` — по чему открывать карточку. */
            id: string;
            title: string;
        };
        AiMessage: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            role: "user" | "assistant";
            text: string;
            card_refs: components["schemas"]["AiCardRef"][];
            /** @description Ссылки на первоисточники под ответом. */
            sources: components["schemas"]["Source"][];
            /** @description `true` — честное «данных нет» (F36). Клиент рисует жёлтым. */
            refused: boolean;
            /** Format: date-time */
            created_at: string;
        };
        AiChat: {
            /** Format: uuid */
            id: string;
            /**
             * @example Чат 23 сентября
             * @example Льготы в ИТМО
             */
            title: string;
            /** Format: date-time */
            created_at: string;
            /**
             * Format: date-time
             * @description Время последней реплики — по нему список идёт от свежих к старым.
             */
            last_message_at: string;
        };
        AiQuestion: {
            text: string;
        };
        /** @description Пара вопрос–ответ и чат, в котором она сохранена. */
        AiExchange: {
            chat: components["schemas"]["AiChat"];
            question: components["schemas"]["AiMessage"];
            answer: components["schemas"]["AiMessage"];
        };
    };
    responses: {
        /** @description Некорректный запрос */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Нет или истёк JWT — клиент повторяет POST /session */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Действие запрещено матрицей прав ТЗ §3.1 */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Объект не найден */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Слишком часто */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description `olympiad_profiles.id` */
        ProfileId: string;
        /** @description `tracker_items.id` */
        TrackerItemId: string;
        /** @description `proposals.id` */
        ProposalId: string;
        /** @description `ai_chats.id`. Чужой чат для участника не существует — 404 (ТЗ F37). */
        ChatId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
